### ISSUE TITLE
New Logo/Icon Proposal

### ISSUE THREAD

**Issue by mansya** [palapon2545/shotClock#1]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by p0ndja** [comment]
👍 Yes, you can.

**Comment by mansya** [comment]
I have designed the logo for this project. What do you think ? do you like it ? if yes let me know and if there are changes please let me know.
![shotclock](https://user-images.githubusercontent.com/33461607/48277997-de37a100-e47e-11e8-88d1-711b4705202b.png)

**Comment by mansya** [comment]
hi sir. how about this offer? are you interested ?
